INSERT INTO Banco (Banco) VALUES ("EL CREDITO HIPOTECARIO NACIONAL DE GUATEMALA");
INSERT INTO Banco (Banco) VALUES ("INMOBILIARIO, S. A.");
INSERT INTO Banco (Banco) VALUES ("DE LOS TRABAJADORES");
INSERT INTO Banco (Banco) VALUES ("INDUSTRIAL, S. A.");
INSERT INTO Banco (Banco) VALUES ("DE DESARROLLO RURAL, S. A.");
INSERT INTO Banco (Banco) VALUES ("INTERNACIONAL, S. A.");
INSERT INTO Banco (Banco) VALUES ("CITIBANK, N.A., SUCURSAL GUATEMALA");
INSERT INTO Banco (Banco) VALUES ("VIVIBANCO, S. A.");
INSERT INTO Banco (Banco) VALUES ("FICOHSA GUATEMALA, S. A.");
INSERT INTO Banco (Banco) VALUES ("PROMERICA, S. A.");
INSERT INTO Banco (Banco) VALUES ("DE ANTIGUA, S. A.");
INSERT INTO Banco (Banco) VALUES ("DE AMERICA CENTRAL, S. A.");
INSERT INTO Banco (Banco) VALUES ("AGROMERCANTIL DE GUATEMALA, S. A.");
INSERT INTO Banco (Banco) VALUES ("G&T CONTINENTAL, S. A.");
INSERT INTO Banco (Banco) VALUES ("AZTECA DE GUATEMALA, S. A.");
INSERT INTO Banco (Banco) VALUES ("INV, S. A.");
INSERT INTO Banco (Banco) VALUES ("CREDICORP, S. A.");


